"use strict";
exports.__esModule = true;
var electron = window['require']('electron');
var remote = electron.remote;
var obs = remote.require('obs-studio-node');
/* Convenient paths to modules */
exports.Global = obs.Global;
exports.Encoder = obs.Encoder;
exports.Source = obs.Source;
exports.InputFactory = obs.InputFactory;
exports.SceneFactory = obs.SceneFactory;
exports.FilterFactory = obs.FilterFactory;
exports.TransitionFactory = obs.TransitionFactory;
exports.OutputFactory = obs.OutputFactory;
exports.ServiceFactory = obs.ServiceFactory;
exports.AudioEncoderFactory = obs.AudioEncoderFactory;
exports.VideoEncoderFactory = obs.VideoEncoderFactory;
exports.AudioFactory = obs.AudioFactory;
exports.VideoFactory = obs.VideoFactory;
exports.DisplayFactory = obs.DisplayFactory;
exports.VolmeterFactory = obs.VolmeterFactory;
exports.FaderFactory = obs.FaderFactory;
exports.VideoFactory = obs.VideoFactory;
exports.ModuleFactory = obs.ModuleFactory;
exports.addItems = obs.addItems;
exports.createSources = obs.createSources;
exports.getSourcesSize = obs.getSourcesSize;
